name: zego_call_flutter
description: ZEGOCLOUD Call.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'
  flutter_screenutil: ^5.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  fluttertoast: ^8.0.9
  flutter_hooks: ^0.18.2
  zego_express_engine: ^2.17.1
  flutter_provider_utilities: ^1.0.4
  loader_overlay: ^2.0.5
  permission_handler: ^9.2.0
  crypto: ^3.0.1
  wakelock: ^0.6.1+1
  package_info_plus: ^1.3.0
  webview_flutter: ^3.0.1
  awesome_notifications: any
  google_sign_in: ^5.2.4
  flutter_background: ^1.1.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  firebase_database: ^9.0.8
  firebase_messaging: ^11.2.11
  cloud_functions: ^3.2.10
  statemachine: ^3.2.0
  result_type: ^0.1.0
  flutter_vibrate: ^1.3.0
  audioplayers: ^0.20.1
  shared_preferences: ^2.0.13
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # for i18n
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/a_dot_burr.jpeg
  #   - assets/images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/key_center.json
    - assets/audio/CallRing.wav

    - assets/images/auth_logo.png
    - assets/images/auth_icon_google.png
    - assets/images/avatar_0.png
    - assets/images/avatar_1.png
    - assets/images/avatar_2.png
    - assets/images/avatar_3.png
    - assets/images/avatar_4.png
    - assets/images/avatar_5.png
    - assets/images/avatar_0_big.png
    - assets/images/avatar_1_big.png
    - assets/images/avatar_2_big.png
    - assets/images/avatar_3_big.png
    - assets/images/avatar_4_big.png
    - assets/images/avatar_5_big.png
    - assets/images/invite_voice.png
    - assets/images/invite_reject_pressed.png
    - assets/images/invite_reject.png
    - assets/images/invite_video_pressed.png
    - assets/images/invite_video.png
    - assets/images/invite_voice_pressed.png
    - assets/images/navigator_back.png
    - assets/images/room_top_quit.png
    - assets/images/title_bar_settings.png
    - assets/images/user_list_default.png
    - assets/images/user_list_video_call.png
    - assets/images/user_list_audio_call.png
    - assets/images/welcome_card_banner.png
    - assets/images/welcome_card_bg.png
    - assets/images/welcome_contact_us.png
    - assets/images/welcome_get_more.png
    - assets/images/setting_next.png
    - assets/images/setting_back.png
    - assets/images/settings_tick.png
    - assets/images/room_overlay_voice_calling.png
    - assets/images/toolbar_bottom_camera_closed.png
    - assets/images/toolbar_bottom_camera_open.png
    - assets/images/toolbar_bottom_cancel.png
    - assets/images/toolbar_bottom_closed.png
    - assets/images/toolbar_bottom_decline.png
    - assets/images/toolbar_bottom_mic_closed.png
    - assets/images/toolbar_bottom_mic_open.png
    - assets/images/toolbar_bottom_speaker_open.png
    - assets/images/toolbar_bottom_speaker_closed.png
    - assets/images/toolbar_bottom_switch_camera.png
    - assets/images/toolbar_bottom_video.png
    - assets/images/toolbar_bottom_voice.png
    - assets/images/toolbar_top_mini.png
    - assets/images/toolbar_top_settings.png
    - assets/images/toolbar_top_switch_camera.png

    - assets/images/2.0x/auth_logo.png
    - assets/images/2.0x/auth_icon_google.png
    - assets/images/2.0x/avatar_0.png
    - assets/images/2.0x/avatar_1.png
    - assets/images/2.0x/avatar_2.png
    - assets/images/2.0x/avatar_3.png
    - assets/images/2.0x/avatar_4.png
    - assets/images/2.0x/avatar_5.png
    - assets/images/2.0x/avatar_0_big.png
    - assets/images/2.0x/avatar_1_big.png
    - assets/images/2.0x/avatar_2_big.png
    - assets/images/2.0x/avatar_3_big.png
    - assets/images/2.0x/avatar_4_big.png
    - assets/images/2.0x/avatar_5_big.png
    - assets/images/2.0x/invite_voice.png
    - assets/images/2.0x/invite_reject_pressed.png
    - assets/images/2.0x/invite_reject.png
    - assets/images/2.0x/invite_video_pressed.png
    - assets/images/2.0x/invite_video.png
    - assets/images/2.0x/invite_voice_pressed.png
    - assets/images/2.0x/navigator_back.png
    - assets/images/2.0x/room_top_quit.png
    - assets/images/2.0x/title_bar_settings.png
    - assets/images/2.0x/user_list_default.png
    - assets/images/2.0x/user_list_video_call.png
    - assets/images/2.0x/user_list_audio_call.png
    - assets/images/2.0x/welcome_card_banner.png
    - assets/images/2.0x/welcome_card_bg.png
    - assets/images/2.0x/welcome_contact_us.png
    - assets/images/2.0x/welcome_get_more.png
    - assets/images/2.0x/setting_next.png
    - assets/images/2.0x/setting_back.png
    - assets/images/2.0x/settings_tick.png
    - assets/images/2.0x/room_overlay_voice_calling.png
    - assets/images/2.0x/toolbar_bottom_camera_closed.png
    - assets/images/2.0x/toolbar_bottom_camera_open.png
    - assets/images/2.0x/toolbar_bottom_cancel.png
    - assets/images/2.0x/toolbar_bottom_closed.png
    - assets/images/2.0x/toolbar_bottom_decline.png
    - assets/images/2.0x/toolbar_bottom_mic_closed.png
    - assets/images/2.0x/toolbar_bottom_mic_open.png
    - assets/images/2.0x/toolbar_bottom_speaker_open.png
    - assets/images/2.0x/toolbar_bottom_speaker_closed.png
    - assets/images/2.0x/toolbar_bottom_switch_camera.png
    - assets/images/2.0x/toolbar_bottom_video.png
    - assets/images/2.0x/toolbar_bottom_voice.png
    - assets/images/2.0x/toolbar_top_mini.png
    - assets/images/2.0x/toolbar_top_settings.png
    - assets/images/2.0x/toolbar_top_switch_camera.png

    - assets/images/3.0x/auth_logo.png
    - assets/images/3.0x/auth_icon_google.png
    - assets/images/3.0x/avatar_0.png
    - assets/images/3.0x/avatar_1.png
    - assets/images/3.0x/avatar_2.png
    - assets/images/3.0x/avatar_3.png
    - assets/images/3.0x/avatar_4.png
    - assets/images/3.0x/avatar_5.png
    - assets/images/3.0x/avatar_0_big.png
    - assets/images/3.0x/avatar_1_big.png
    - assets/images/3.0x/avatar_2_big.png
    - assets/images/3.0x/avatar_3_big.png
    - assets/images/3.0x/avatar_4_big.png
    - assets/images/3.0x/avatar_5_big.png
    - assets/images/3.0x/invite_voice.png
    - assets/images/3.0x/invite_reject_pressed.png
    - assets/images/3.0x/invite_reject.png
    - assets/images/3.0x/invite_video_pressed.png
    - assets/images/3.0x/invite_video.png
    - assets/images/3.0x/invite_voice_pressed.png
    - assets/images/3.0x/navigator_back.png
    - assets/images/3.0x/room_top_quit.png
    - assets/images/3.0x/title_bar_settings.png
    - assets/images/3.0x/user_list_default.png
    - assets/images/3.0x/user_list_video_call.png
    - assets/images/3.0x/user_list_audio_call.png
    - assets/images/3.0x/welcome_card_banner.png
    - assets/images/3.0x/welcome_card_bg.png
    - assets/images/3.0x/welcome_contact_us.png
    - assets/images/3.0x/welcome_get_more.png
    - assets/images/3.0x/setting_next.png
    - assets/images/3.0x/setting_back.png
    - assets/images/3.0x/settings_tick.png
    - assets/images/3.0x/room_overlay_voice_calling.png
    - assets/images/3.0x/toolbar_bottom_camera_closed.png
    - assets/images/3.0x/toolbar_bottom_camera_open.png
    - assets/images/3.0x/toolbar_bottom_cancel.png
    - assets/images/3.0x/toolbar_bottom_closed.png
    - assets/images/3.0x/toolbar_bottom_decline.png
    - assets/images/3.0x/toolbar_bottom_mic_closed.png
    - assets/images/3.0x/toolbar_bottom_mic_open.png
    - assets/images/3.0x/toolbar_bottom_speaker_open.png
    - assets/images/3.0x/toolbar_bottom_speaker_closed.png
    - assets/images/3.0x/toolbar_bottom_switch_camera.png
    - assets/images/3.0x/toolbar_bottom_video.png
    - assets/images/3.0x/toolbar_bottom_voice.png
    - assets/images/3.0x/toolbar_top_mini.png
    - assets/images/3.0x/toolbar_top_settings.png
    - assets/images/3.0x/toolbar_top_switch_camera.png
